### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by Ashish117** [ofarukcaki/jsonfind#1] opened 2019-12-15 13:22 UTC
When i run the same json data in run kit it works but when i get the same data from MongoDB using mongoose Data.find(), it will show cannot convert object to primitive value.
@ofarukcaki

**Comment by ofarukcaki** [comment] 2019-12-15 13:30
I checked the [mongoose's docs](https://mongoosejs.com/docs/api.html#model_Model.find) and find() methods seems returning a «Query».  I don't know what is the structure of that return value. You should check it and make sure its either object or array of objects

**Comment by Ashish117** [comment] 2019-12-15 13:36
I also tried stringifying that data and that too didn't help.
This is how the mongoose data outputs:

```
[
  {
    "bulk": [
      [
        [
          {
            "_id": "5df623aefc5a3b0f8dbf0f7d",
            "title": " XTC-331 ADAPTADOR DE VIDEO MINI DISPLAYPORT HDMI HEMBRA 15 CM BLANCO ",
            "price": " $8.00 ",
            "stock": " Stock: 2  ",
            "code": "Código: 01002XT001 ",
            "url": "https://www.cyccomputer.pe/adaptadores/7738-xtc-331-adaptador-de-video-mini-displayport-hdmi-hembra-15-cm-blanco.html",
            "img": "https://www.cyccomputer.pe/16415-home_default/xtc-331-adaptador-de-video-mini-displayport-hdmi-hembra-15-cm-blanco.jpg"
          }
        ],
        [
          {
            "_id": "5df623aefc5a3b0f8dbf0f80",
            "title": " CARGADOR 12V 1A ",
            "price": " $7.00 ",
            "stock": " Stock: 6  ",
            "code": "Código: 02013GN006 ",
            "url": "https://www.cyccomputer.pe/cargadores/8376-cargador-12v-1a.html",
            "img": "https://www.cyccomputer.pe/16923-home_default/cargador-12v-1a.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f7f",
            "title": " CARGADOR PARA MONITOR 12V 2A ",
            "price": " $9.41 ",
            "stock": " Stock: 2  ",
            "code": "Código: 02013GN026 ",
            "url": "https://www.cyccomputer.pe/cargadores/12470-cargador-para-monitor-12v-2a.html",
            "img": "https://www.cyccomputer.pe/18622-home_default/cargador-para-monitor-12v-2a.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f7e",
            "title": " CARGADOR PARA MONITOR 12V 3A ",
            "price": " $9.41 ",
            "stock": " Stock: 2  ",
            "code": "Código: 02013GN027 ",
            "url": "https://www.cyccomputer.pe/cargadores/12471-cargador-para-monitor-12v-3a.html",
            "img": "https://www.cyccomputer.pe/18623-home_default/cargador-para-monitor-12v-3a.jpg"
          }
        ]
      ],
      [
        [
          {
            "_id": "5df623aefc5a3b0f8dbf0f8a",
            "title": "CAMARA WEB MICRONICS OTHELO ( MIC W360BR ) NEGRO C/ ROJO",
            "price": "$ 11.50",
            "stock": "Stock 6",
            "code": "Stock 6",
            "url": "https://www.impacto.com.pe/web/producto/9385/camara-web-micronics-othelo-mic-w360br-negro-c-rojo",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_191015.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f89",
            "title": "CAMARA WEB MICROSOFT LIFECAM HD-3000 ( T3H-00011 ) HD | C/ MICROFONO",
            "price": "$ 30.50",
            "stock": "Stock 6",
            "code": "Stock 6",
            "url": "https://www.impacto.com.pe/web/producto/8359/camara-web-microsoft-lifecam-hd-3000-t3h-00011-hd-c-microfono",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_191125.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f88",
            "title": "CAMARA WEB RAZER KIYO ( RZ19-02320100-R3U1 ) 720P HD | LED- BLANCA",
            "price": "$ 112.00",
            "stock": "Stock 4",
            "code": "Stock 4",
            "url": "https://www.impacto.com.pe/web/producto/6569/camara-web-razer-kiyo-rz19-02320100-r3u1-720p-hd-led-blanca",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_191211.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f87",
            "title": "CAMARA WEB LOGITECH BRIO ( 960-001105 ) 1080P HD | 4K ULTRA",
            "price": "$ 158.00",
            "stock": "Stock 10 +",
            "code": "Stock 10 +",
            "url": "https://www.impacto.com.pe/web/producto/6561/camara-web-logitech-brio-960-001105-1080p-hd-4k-ultra",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_191334.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f86",
            "title": "CAMARA WEB LOGITECH C922 PRO ( 960-001087 ) 1080P HD",
            "price": "$ 80.00",
            "stock": "Stock 5",
            "code": "Stock 5",
            "url": "https://www.impacto.com.pe/web/producto/6559/camara-web-logitech-c922-pro-960-001087-1080p-hd",
            "img": "https://www.impacto.com.pe/web/imagenes_web/camara-web-1_20180131_212456.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f85",
            "title": "CAMARA WEB LOGITECH C930E ( 960-000971 ) 1080P HD",
            "price": "$ 119.00",
            "stock": "Stock 4",
            "code": "Stock 4",
            "url": "https://www.impacto.com.pe/web/producto/5244/camara-web-logitech-c930e-960-000971-1080p-hd",
            "img": "https://www.impacto.com.pe/web/imagenes_web/929_20170606_111527.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f84",
            "title": "CAMARA WEB LOGITECH C525 ( 960-000715 ) 720P HD",
            "price": "$ 48.00",
            "stock": "Stock 10 +",
            "code": "Stock 10 +",
            "url": "https://www.impacto.com.pe/web/producto/4831/camara-web-logitech-c525-960-000715-720p-hd",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_192103.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f83",
            "title": "CAMARA WEB GENIUS 1000X ( 32200223101 ) 720P HD",
            "price": "$ 15.00",
            "stock": "Stock 6",
            "code": "Stock 6",
            "url": "https://www.impacto.com.pe/web/producto/4136/camara-web-genius-1000x-32200223101-720p-hd",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_191443.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f82",
            "title": "CAMARA WEB LOGITECH C920 PRO ( 960-000764 ) 1080P HD",
            "price": "$ 79.00",
            "stock": "Stock 2",
            "code": "Stock 2",
            "url": "https://www.impacto.com.pe/web/producto/3618/camara-web-logitech-c920-pro-960-000764-1080p-hd",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_191533.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f81",
            "title": "CAMARA WEB LOGITECH C270 ( 960-000694 ) 720P HD",
            "price": "$ 28.00",
            "stock": "Stock 10 +",
            "code": "Stock 10 +",
            "url": "https://www.impacto.com.pe/web/producto/2400/camara-web-logitech-c270-960-000694-720p-hd-",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_191632.jpg"
          }
        ],
        [
          {
            "_id": "5df623aefc5a3b0f8dbf0f8e",
            "title": "CAMARA DE VIGILANCIA DAHUA EYEBALL ( DH-HAC-HDW1200RN-0280B-S4 ) DOMO | HD 1080P",
            "price": "$ 24.00",
            "stock": "Stock 8",
            "code": "Stock 8",
            "url": "https://www.impacto.com.pe/web/producto/9224/camara-de-vigilancia-dahua-eyeball-dh-hac-hdw1200rn-0280b-s4-domo-hd-1080p",
            "img": "https://www.impacto.com.pe/web/imagenes_web/cam-1_20190529_151603.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f8d",
            "title": "CAMARA DE VIGILANCIA DAHUA DOME ( DH-HDBW1200RN-Z ) DOMO | HD 1080P",
            "price": "$ 63.00",
            "stock": "Stock 1",
            "code": "Stock 1",
            "url": "https://www.impacto.com.pe/web/producto/9223/camara-de-vigilancia-dahua-dome-dh-hdbw1200rn-z-domo-hd-1080p",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_193131.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f8c",
            "title": "CAMARA DE VIGILANCIA LOGAN ( LX1B ) TUBO | 720P",
            "price": "$ 15.50",
            "stock": "Stock 7",
            "code": "Stock 7",
            "url": "https://www.impacto.com.pe/web/producto/7866/camara-de-vigilancia-logan-lx1b-tubo-720p",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1_20190816_193732.jpg"
          },
          {
            "_id": "5df623aefc5a3b0f8dbf0f8b",
            "title": "CAMARA DE VIGILANCIA DAHUA HFW1000RN ( DH-HAC-HFW1000RN-0280B-S3 ) TUBO | HD 720P",
            "price": "$ 14.50",
            "stock": "Stock 1",
            "code": "Stock 1",
            "url": "https://www.impacto.com.pe/web/producto/7685/camara-de-vigilancia-dahua-hfw1000rn-dh-hac-hfw1000rn-0280b-s3-tubo-hd-720p",
            "img": "https://www.impacto.com.pe/web/imagenes_web/1-2_20190816_193714.jpg"
          }
        ]
      ]
    ],
    "_id": "5df623aefc5a3b0f8dbf0f7c",
    "__v": 0
  }
]
```

**Comment by ofarukcaki** [comment] 2019-12-15 13:43
You should stringify, the returned data structure is valid for this module and sa you said it works on runkit. 

So, the problem is most probably caused by running the jsonFind without getting the response from MongoDB, I mean it's async and most likely you are not waiting for it to be completed.

If you are in async code block you should await the find() call, otherwise you should use the jsonFind inside .then() block

**Comment by Ashish117** [comment] 2019-12-15 13:49
@ofarukcaki 
Still the same. 
```
const results = await Data.find().then(dat => {
            jsonFind.All(JSON.stringify(dat), "title");
          });
          console.log(results)
          res.status(200).json(results);
```

It would be great if you can help because it's urgent. I want to search the json for products for example if i search intel it should show all objects with intel. i am planning to do this with jsonFInd and Fuse.js because the Json i got is kind of hard to get each data

**Comment by ofarukcaki** [comment] 2019-12-15 13:55
You are doing it really wrong,

1. You **shouldn't** stringify the data object
2. You can't use both **await** and **.then()** keywords together
3. jsonFind.All method returns the results and you should **assign it into a variable**

Try this:
```javascript
const data = await Data.find();

const results = jsonFind.All(data, "title");

console.log(results)
res.status(200).json(results);
```

**Comment by Ashish117** [comment] 2019-12-15 14:02
@ofarukcaki 
Again "Cannot convert object to primitive value"

**Comment by Ashish117** [comment] 2019-12-15 14:36
@ofarukcaki I also tried saving the data in the same js file and it prints  {}

**Closed as completed** 2020-07-12 17:51 UTC
